### ISSUE TITLE
As a twitter user, I would like the bot to tweet out Bitcoin and Ethereum price every hour with a chart that contains daily candles. 

### ISSUE THREAD

**Issue by JordanDworaczyk** [JordanDworaczyk/Pricebots#59]
Please answer all of the questions before submitting your issue. The answers that you provide will help guide the _Discussion_ phase of our workflow process - thanks!

**(1) Why are you submitting this issue?**
- [ ] I have found a bug and would like to report it.
- [x] I would like to suggest a feature/enhancement.

_Please describe the bug or feature/enhancement in detail below:_
The bot should be able to tweet out the price of Ethereum and Bitcoin together. The chart should contain daily candles, and contain approximately the same amount of candles that the hourly chart contains _(168 candles)_. Each tweet should be tweeted hourly, and should contain the current price information of the given cryptocurrency, in this case, Bitcoin and Ethereum. 

# Features/Enhancements
**#(1) If you are submitting a feature request, then please explain why you would like the feature to be added to Pricebots. Why is this enhancement a good thing to have?**  
_Please explain why the feature should be incorporated into the project below:_
This feature should be added to Pricebots because there is a demand on twitter for houlry updates on the daily priceaction of Bitcoin and Ethereum. You can see this demand in this conversation that took place on Twitter [here](https://twitter.com/LDrogen/status/882720441659523075). 

**(2) What is a possible solution for _implementing_ the feature that you are requesting?**
_Please provide a detailed implementation below:_
We could add a configuration setting that configures the bot to tweet out a certain amount of cryptocurrencies. Then, we add a nother configuration for tweeting a certain type of candlesticks (e.g. hourly, daily, etc..). The yaml file might look something like this: 
```yaml
 1:
  consumer_key: secret
  consumer_secret: secret
  access_key: secret
  access_secret: secret
  coin_name: eth
  full_name: Ethereum
  increasing_color: "#19cf86"
  decreasing_color: "#cf1962"
  candlestick: daily 
  update_time: hourly
  tweet_coins: 
    - Ethereum
    - Bitcoin 

```
Then, once the yaml file is configured correctly, the bot will pass the parameters to a function that can tweet two charts in a single tweet. The function could also provide the current price action information in the tweet's status. 

**(3) What changes would need to be required for your feature/enhancement to be considered done?**
_Please provide the requirements below:_
The bot should be able to tweet a chart that contains daily candles of both Bitcoin and Ethereum in order for the enhancement to be considered done. The bot should also tweet out a tweet every hour, and should contain a status of the last price data for each coin.
